SELECT *
FROM EMPLOYEES E
WHERE E.SALARY > (
SELECT AVG(SALARY)
FROM EMPLOYEES E2
WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID
);

SELECT *
FROM DEPARTMENTS D
WHERE (SELECT AVG(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID = D.DEPARTMENT_ID)
= (
SELECT MAX(AVG(SALARY))
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID);

SELECT *
FROM EMPLOYEES E
WHERE DEPARTMENT_ID = 80
AND EXISTS (
SELECT 1
FROM JOBS
WHERE JOB_ID = 'SA_REP'
AND JOB_ID = E.JOB_ID);
