select * from alumno
desc alumno;
insert into alumno values
('2025','lUCIA','Aguilar');
select * from BITACORA_ALUMNO
delete ALUMNO
where carne ='2025'
alter table BITACORA_ALUMNO
add carne number(15);
CREATE TABLE BITACORA_ALUMNO (
USUARIO VARCHAR2(30),
FECHA DATE
)
SELECT * FROM BITACORA_ALUMNO
CREATE OR REPLACE TRIGGER
TR_INGRESO_ALUMNO
BEFORE INSERT
ON ALUMNO
FOR EACH ROW
BEGIN
INSERT INTO BITACORA_ALUMNO
VALUES (USER,SYSDATE,'INSERT',:new.carne);
END;
CREATE OR REPLACE TRIGGER
TR_ELIMINACION_ALUMNO
BEFORE DELETE
ON ALUMNO
FOR EACH ROW
BEGIN
INSERT INTO BITACORA_ALUMNO
VALUES (USER,SYSDATE,'DELETE',:old.carne);
END;
